
<?php echo Tag::js("icheck/js/icheck");?>
<?php echo Tag::js("administrador/representante/listar");?>
<?php echo Tag::js("selectize/js/standalone/selectize");?>

<div class="row">
  <div class="col-md-12">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title pull-left"> Lista </h3>
        <br><p>
        <br>
        <hr>
	<div class="box box-default">
	    <div class="box-header with-border">
	      <h3 class="box-title">Filtros</h3>
	      <div class="box-tools pull-right">
		<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
		<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
	      </div>
	    </div>
	    <div class="box-body">
		<div class="row">
		    <div class="col-md-4">
			<div class="form-group">
			    <label>Establecimiento</label>
			    <select id="establecimientos" selectize >
				<option value=""></option>
				<?php 
				    foreach($filtro_est as $e):
					echo "<option value='".$e->id."'>".$e->nombre."</option>";
				    endforeach;
				?>
			    </select>
			</div>
		    </div>
		    
		    <div class="col-md-4">
			<div class="form-group">
			    <label>Profesor</label>
			    <div class="input-group">
				<span class="input-group-addon"><i class="fa fa-user"></i></span>
				<input id="profesor" type="text" class="form-control" placeholder="Profesor">
			    </div>
			</div>
		    </div>
		    
		    <div class="col-md-4">
			<div class="form-group">
			    <label>Alumno</label>
			    <div class="input-group">
				<span class="input-group-addon"><i class="fa fa-user"></i></span>
				<input type="text" class="form-control" placeholder="Alumno">
			    </div>
			</div>
		    </div>
		</div>
		<div class="row">
		     <div class="col-md-4">
			<div class="form-group">
			    <label>Estado Compra</label>
			    <div class="form-group">
			   <ul class="list">
			    <li>
			      <input value="" tabindex="14" type="radio" id="flat-radio-1"  name="estado" checked>
			      <label for="flat-radio-1">Todos</label>
			    </li>
			    <li>
			      <input value="0" tabindex="15" type="radio" id="flat-radio-1" name="estado" >
			      <label for="flat-radio-1">Disponibles</label>
			    </li>
			    <li>
			      <input value="1" tabindex="16" type="radio" id="flat-radio-2" name="estado" >
			      <label for="flat-radio-2">Comprados</label>
			    </li>
			  </ul>
			  </div>
			</div>
		    </div>
		</div>
		<button id="buscar" class="btn btn-success"  /><i class="fa fa-search"> Buscar </i></button>
	    </div>
	</div>
        <div class="table-responsive col-md-12">
          <table id="tabla" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>RBD</th>
		    <th>Nombre colegio</th>
		    <th>Nombre profesor</th>
		    <th>Rut</th>
		    <th>Alumnos(s)</th>
		    <th>Opciones</th>
                </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!--Modal para ver los usuarios-->
<?php echo View::partial("modal_representante")?>