<br>
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 col-xs-12">
    <div class="card bg-light mb-12">
      <div class="card-header">Identificación del alumno - Ediciones SM</div>
      <div class="card-body text-dark">
        <h2 class="card-title">Paso 2 / 2</h2>
        <form id="estudiante">
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <label class="col-form-label" for="inputDefault">RUT</label>
                <input type="text" class="form-control" placeholder="11.111.111-1" id="inputDefault">
              </div>
            </div>
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <label class="col-form-label" for="inputDefault">NOMBRE COMPLETO</label>
                <input type="text" class="form-control" placeholder="Papelucho Paletin" id="inputDefault">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <label for="exampleInputEmail1">CORREO</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="papelucho@correo.com">
                <small id="emailHelp" class="form-text text-muted">No compartiremos tu correo.</small>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6">
              <div class="form-group">
                <label for="exampleSelect1">CURSO</label>
                <select class="form-control" id="exampleSelect1">
                  <option value="1">Primero Básico</option>
                  <option value="2">Segundo Básico</option>
                  <option value="3">Tercero Básico</option>
                  <option value="4">Cuarto Básico</option>
                  <option value="5">Quinto Básico</option>
                  <option value="6">Sexto Básico</option>
                  <option value="7">Séptimo Básico</option>
                  <option value="8">Octavo Básico</option>
                  <option value="9">Primero Medio</option>
                  <option value="10">Segundo Medio</option>
                  <option value="11">Tercero Medio</option>
                  <option value="12">Cuarto Medio</option>
                </select>
              </div>
            </div>
          </div>
        </form>
        <!--<form id="alumno" class="form-inline">
          <fieldset>
            <legend>Ingrese los datos para el alumno al que le comprará los libros</legend>
            <div class="form-group">
              <label class="col-form-label" for="inputDefault">RUT</label>
              <input type="text" class="form-control" placeholder="11.111.111-1" id="inputDefault">
            </div>
            <div class="form-group">
              <label class="col-form-label" for="inputDefault">NOMBRE COMPLETO</label>
              <input type="text" class="form-control" placeholder="Papelucho Paletin" id="inputDefault">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">CORREO ELECTRÓNICO</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="papelucho@correo.com">
              <small id="emailHelp" class="form-text text-muted">No compartiremos tu correo.</small>
            </div>
            <div class="form-group">
              <label for="exampleSelect1">Example select</label>
              <select class="form-control" id="exampleSelect1">
                <option value="1">Primero Básico</option>
                <option value="2">Segundo Básico</option>
                <option value="3">Tercero Básico</option>
                <option value="4">Cuarto Básico</option>
                <option value="5">Quinto Básico</option>
                <option value="6">Sexto Básico</option>
                <option value="7">Séptimo Básico</option>
                <option value="8">Octavo Básico</option>
                <option value="9">Primero Medio</option>
                <option value="10">Segundo Medio</option>
                <option value="11">Tercero Medio</option>
                <option value="12">Cuarto Medio</option>
              </select>
            </div>
            <button type="button" name="anterior" class="btn btn-primary">Anterior</button>
            <button type="submit" class="btn btn-primary">Siguiente</button>
          </fieldset>
        </form>-->
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>
