<br>
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 col-xs-12">
    <div class="card bg-light mb-12">
      <div class="card-header">Identificación del apoderado - Ediciones SM</div>
      <div class="card-body text-dark">
        <h2 class="card-title">Paso 1 / 2</h2>
        <form id="identidad">
          <fieldset>
            <legend>Identificación del apoderado</legend>
            <div class="form-group">
              <label class="col-form-label" for="inputDefault">RUT</label>
              <input type="text" class="form-control" placeholder="11.111.111-1" id="inputDefault">
            </div>
            <div class="form-group">
              <label class="col-form-label" for="inputDefault">NOMBRE COMPLETO</label>
              <input type="text" class="form-control" placeholder="Papelucho Paletin" id="inputDefault">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">CORREO ELECTRÓNICO</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="papelucho@correo.com">
              <small id="emailHelp" class="form-text text-muted">No compartiremos tu correo.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">CONFIMAR CORREO ELECTRÓNICO</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="papelucho@correo.com">
            </div>
            <button type="button" name="anterior" class="btn btn-primary">Anterior</button>
            <button type="submit" class="btn btn-primary">Siguiente</button>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>
