<script>
  $(document).ready(function(){
    $('#volver').click(function(){
      $('#cap').empty().load('usuario/principal');
    });
    $('#rut').blur(function(){
      var rut = $('#rut').val();
      $.ajax({
        url: 'usuario/buscar',
        type: 'POST',
        cache: false,
        data: {"rut":rut},
        success: function(result){
          console.log(result);
          //console.log(result['nombre'] +' '+result['correo']);
          $("#nombre").attr("value", result['nombre']);
          $("#nombre").prop("disabled", true);
          $('.email').attr("value", result['email']);
          $(".email").prop("disabled", true);
        },
        error: function (xhr, ajaxOptions, thrownError) {
          console.log(xhr.status);
          console.log(thrownError);
        }
      })
    });
  })
</script>
    <div class="card bg-light mb-12 cont-sombra">
      <div class="card-header">Identificación del apoderado - Ediciones SM</div>
      <div class="card-body text-dark">
        <h2 class="card-title">Paso 1 / 2</h2>
        <form id="identidad">
          <fieldset>
            <legend>Identificación del <?php echo $tipo ?></legend>
            <div class="form-group">
              <label class="col-form-label" for="inputDefault">RUT</label>
              <input id="rut" name="rut" required type="text" class="form-control" placeholder="11.111.111-1" id="inputDefault">
            </div>
            <div class="form-group">
              <label class="col-form-label" for="inputDefault">NOMBRE COMPLETO</label>
              <input id="nombre" name="nombre" type="text" class="form-control" placeholder="Papelucho Paletin" id="inputDefault">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">CORREO ELECTRÓNICO</label>
              <input type="email" class="form-control email" aria-describedby="emailHelp" placeholder="papelucho@correo.com">
              <small id="emailHelp" class="form-text text-muted">No compartiremos tu correo.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">CONFIMAR CORREO ELECTRÓNICO</label>
              <input type="email" class="form-control email" aria-describedby="emailHelp" placeholder="papelucho@correo.com">
            </div>
            <button id="volver" type="button" name="anterior" class="btn btn-primary">Anterior</button>
            <button type="submit" class="btn btn-primary">Siguiente</button>
          </fieldset>
        </form>
      </div>
    </div>
    <?php //echo Tag::js('validarut') ?>
