<div class="row">
  <div class="col-md-12">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title"> Editar usuario </h3>
        <div class="box-body">
          <form id="editar_usuario" >
            <input id="usuario" name="id" type="text" class="form-control hidden"  value="<?php echo $usuario->id?>">
            <h4>Nombre</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-user" style="color:red"></i></span>
              <input id="nombre" name="nombre" type="text" class="form-control" placeholder="Ingrese Nombre" value="<?php echo $usuario->nombre ?>">
            </div>
            <br>
            <h4>Rut</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-address-card-o" style="color:red"></i></span>
              <input id="rut" minlength="9" maxlength="10" name="rut" type="text" class="form-control" placeholder="Ingrese Rut sin Digito Verificador" value="<?php echo $usuario->rut?>">
            </div>
            <br>
            <h4>Email</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-envelope" style="color:red"></i></span>
              <input id="correo" minlength="3" maxlength="80" name="correo" type="text" class="form-control" placeholder="Ingrese Email" value="<?php echo $usuario->email ?>">
            </div>
            <br>
            <h4>Telefono</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-envelope" style="color:red"></i></span>
              <input id="telefono" minlength="3" maxlength="80" name="telefono" type="text" class="form-control" placeholder="Ingrese telefono" value="<?php echo $usuario->telefono ?>">
            </div>
            <br>
          </form>
          <button  class="btn btn-success guardar pull-right"  />Actualizar</button>
          <span class=" ml-1 pull-right"> &nbsp; &nbsp; </span>
          <button  class="btn btn-default volver  pull-right"  />Volver</button>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    //console.log(id + nombre + rut + correo);
    $(".guardar").click(function(){
      var id = $("#usuario").val();
      var nombre = $("#nombre").val();
      var rut = $("#rut").val();
      var correo = $("#correo").val();
      var tel = $("#telefono").val();
      $.ajax({
        type: "POST",
        cache: false,
        url: "../editar_usuario",
        data: {"id": id, "nombre":nombre, "rut":rut, "correo":correo, "tel": tel},
        success: function(result){
          if(result == 1){
            console.log("usuario actualizado");
            swal({
               title: "Usuario actualizado correctamente!",
               text: "Gracias por utilizar nuestro sistema",
               type: "success",
               timer: 3000
             });
          }else{
            console.log("error"); //Colocar el sweet alert
            swal(
                  'Error al editar',
                  'No se pudieron editar los datos, vuelva a intentar',
                  'error'
                );
          }
        }
      })
    })
  })
</script>
