<!-- CSS se cargara en el template, primero carga el view luego el template -->
<?php Tag::css('../bower_components/datatables.net-bs/css/dataTables.bootstrap.min') ?>
<?php echo Tag::js('administrador/usuarios/listar') ?>

<div class="row">
  <div class="col-md-12">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title pull-left"> Lista de Apoderados </h3>
        <br><p>
        <button  class="btn btn-success nuevo_usuario pull-right">
          <i class="fa fa-plus pull-left"> Nuevo </i>
        </button>
        <br>
        <hr>
        <div class="table-responsive col-md-12">
          <table id="tabla_usuarios" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>ID</th>
		    <th>Rut</th>
                    <th>Nombre</th>
		    <th>Tipo</th>
                    <th>Hijos</th>
                </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!--Modal para ver los usuarios-->
<div class="modal fade bd-example-modal-lg" id="hijos_usuario" tabindex="-1" role="dialog" aria-labelledby="direccionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
	<div class="modal-content ">
	    <div class="modal-header">
		<h5 class="modal-title" id="direccionModalLabel"><label class="titulo"></label></h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
		    <span aria-hidden="true">&times;</span>
		</button>
	    </div>
	    <div class="modal-body">
		<fieldset>
		    <div class="form-bottom">
			<div class="form-group">
			    <form id="datos_despacho" class="form-horizontal">
				<div class="col-md-12">
				    <div class="row">
					<div class="col-md-6">
					    <table class="dataTable" style="border: 1px solid #1b6d85">
					       <thead>
						    <tr><th style="width: 13%; background-color: #31b0d5; border-right:1px solid #1b6d85; color: #FFF">Nombre</th><td> <label class="nombre_usuario"></label> </td></tr>
						    <tr><th style="width: 13%; background-color: #31b0d5; border-right:1px solid #1b6d85; color: #FFF">Rut</th> <td> <label class="rut_usuario"></label> </td></tr>
						    <tr><th style="width: 13%; background-color: #31b0d5; border-right:1px solid #1b6d85; color: #FFF">Cantidad Alumnos</th> <td> <label class="cantidad_alumnos"></label> </td></tr>
						</thead>
					    </table>
					</div>
<!--					<div class="col-md-12">
					    <div class="col-md-2">
						<label for="inputEmail3" class="control-label">Ciudad</label>
					    </div>
					    <div class="col-md-10">
						<input type="text" id="ciudad"  class="form-control form-sm"><br>
					    </div>
					</div>-->
					<div class="col-md-12">    
					    <ul class="nav nav-tabs">
						<li class="active" ><a href="#" style="background-color: #31b0d5; border: 1px solid #1b6d85; color: #FFF"><i class="fa fa-graduation-cap"></i> Alumno(s)</a></li>
						<table class="dataTable hijos_dt" style="border: 1px solid #1b6d85">
						    <tr style="background-color: #31b0d5;">
						    <th style="border-right:1px solid #1b6d85; color: #FFF">Nombre</th>
						    <th style="color: #FFF">Rut</th>
						    </tr>
						    <tbody class="datos_hijos">

						    </tbody>
						</table>
					    </ul>
					</div>
				    </div>
				</div>
			    </form>
			</div>
		    </div>
		</fieldset>
		<div class="modal-footer">
		    <div class="col-md-12">
			<div class="row">
			    <div class="col-md-5">
				    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar ventana</button>
			    </div>
			    <span class="col-md-2"></span>
			    <div class="col-md-5">
				<button id="pagar" class="btn btn-primary form-control hidden pagar">Ir a pagar</button>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>