<div class="row">
  <div class="col-md-12">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title"> Crear Alumno </h3>
        <div class="box-body">
          <form id="editar_usuario" >
            <input id="alumno" name="id" type="text" class="form-control hidden"  value="<?php echo $alumno->id?>">
            <h4>Nombre</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-user" style="color:red"></i></span>
              <input id="nombre" name="nombre" type="text" class="form-control" placeholder="Ingrese nombre y apellido del alumno" value="<?php echo $alumno->nombre ?>">
            </div>
            <br>
            <h4>RUT</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-address-card-o" style="color:red"></i></span>
              <input id="rut" maxlength="50" name="rut" type="text" class="form-control" placeholder="Ingrese rut sin puntos ni guiones ni dígito verificador" value="<?php echo $alumno->rut ?>">
            </div>
            <br>
            <h4>Email</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-envelope" style="color:red"></i></span>
              <input id="email" minlength="3" maxlength="80" name="telefono" type="text" class="form-control" placeholder="Ingrese correo del alumno" value="<?php echo $alumno->email ?>">
            </div>
            <br>
            <h4>Colegio</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-graduation-cap" style="color:red"></i></span>
              <select id="colegio" class="form-control" name="tipo">
                <?php foreach($colegios as $key => $valor): ?>
                  <?php if($valor->id == $alumno->establecimiento_id): ?>
                    <option value="<?php echo $valor->id ?>" selected><?php echo $valor->nombre ?></option>
                  <?php else: ?>
                    <option value="<?php echo $valor->id ?>"><?php echo $valor->nombre ?></option>
                  <?php endif ?>
                <?php endforeach ?>
              </select>
            </div>
            <br>
            <h4>Curso</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-chevron-circle-up" style="color:red"></i></span>
              <select id="curso" class="form-control" name="tipo">
                <?php foreach($cursos as $key => $valor): ?>
                  <?php if($valor->id == $alumno->curso): ?>
                    <option value="<?php echo $valor->id ?>" selected><?php echo $valor->nombre ?></option>
                  <?php else: ?>
                    <option value="<?php echo $valor->id ?>"><?php echo $valor->nombre ?></option>
                  <?php endif ?>
                <?php endforeach ?>
              </select>
            </div>
            <br>
          </form>
          <button  class="btn btn-success guardar pull-right"  />Editar alumno</button>
          <span class=" ml-1 pull-right"> &nbsp; &nbsp; </span>
          <button  class="btn btn-default volver  pull-right"  />Volver</button>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".guardar").click(function(){
      var id = $("#alumno").val();
      var nombre = $("#nombre").val();
      var rut = $("#rut").val();
      var email = $("#email").val();
      var colegio = $("#colegio").val();
      var curso = $("#curso").val();
      console.log(nombre + rut + email + colegio + curso);
      $.ajax({
        type: "POST",
        cache: false,
        url: "../editar_usuario",
        data: {"id":id, "nombre":nombre, "rut":rut, "correo":email, "colegio":colegio, "curso":curso},
        success: function(result){
          if(result == 1){
            console.log("alumno editado");
            swal({
               title: "Alumno editado correctamente!",
               text: "En breves momentos serás redireccionado",
               type: "success",
               timer: 3000
             });
          }else{
            console.log("error"); //Colocar el sweet alert
            swal(
                  'Error al editar el alumno',
                  'No se pudieron ingresar los datos, vuelva a intentar',
                  'error'
                );
          }
        }
      })
    });
    $(".volver").click(function(){
      location.href = "https://localhost/smcompra/administrador/alumnos";
    })
  })
</script>
