<!-- CSS se cargara en el template, primero carga el view luego el template -->
<?php Tag::css('../bower_components/datatables.net-bs/css/dataTables.bootstrap.min') ?>
<script type="text/javascript">
  $(document).ready(function() {
    var table = $('#tabla_productos').DataTable( {
      "ajax": {
               "url": "productos/listar_productos",
               "dataType": "json",
               "cache": false,
             },
      dom: 'Bfrtip',
      "buttons": [
         {"extend": 'excel', "text":'<i class="fa fa-download" aria-hidden="true"></i>&nbsp; &nbsp; Exportar Excel',"className": 'btn btn-success pull-center'}
      ],
      "columns": [
          { "data": "id" },
      	  { "data": "descripcion" },
      	  { "data": "proyecto" },
      	  { "data": "tipo" },
          { "data": "nombre" },
          { "data": "codigo"},
          { "data": "valor"},
          { "data": "acciones"}
      ]
    });
    $("#tabla_productos").on("click", ".editar", function(){
      var id = $(this).attr("value");
      location.href = "https://localhost/smcompra/administrador/productos/editar/"+id;
    });

    $("tabla_productos").on("click", "#agregar", function(){
      location.href = "https://localhost/smcompra/administrador/productos/agregar/"+id;
    })
  });
</script>
<div class="row">
  <div class="col-md-12">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title pull-left"> Lista de Productos activos </h3>
        <br>
        <br>
        <button id="agregar" type="button" name="button" class="btn btn-success">Agregar nuevo producto</button>
        <hr>
        <div class="table-responsive col-md-12">
          <table id="tabla_productos" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>ID</th>
		                <th>Descripcion</th>
            		    <th>Proyecto</th>
            		    <th>Tipo</th>
                    <th>Nombre</th>
                    <th>Código SAP</th>
                    <th>Precio</th>
                    <th>Acciones</th>
                </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
