<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top" style="background-color:#222d32">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
  </a>

  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      <li class="dropdown user user-menu">
        <p>
        <div class="col-sm-4" >
          <?php echo Html::link('administrador/index/cerrar', 'Cerrar sesión', 'class="btn btn-danger"') ?>
        </div>
      </li>
    </ul>
  </div>
</nav>
