<div class="modal fade bd-example-modal-lg" id="hijos_usuario" tabindex="-1" role="dialog" aria-labelledby="hijoModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
	<div class="modal-content ">
	    <div class="modal-header">
		<h5 class="modal-title" id="hijoModalLabel"><label class="titulo"></label></h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
		    <span aria-hidden="true">&times;</span>
		</button>
	    </div>
	    <div class="modal-body">
		<fieldset>
		    <div class="form-bottom">
			<div class="form-group">
			    <form id="datos_despacho" class="form-horizontal">
				<div class="col-md-12">
				    <div class="row">
					<div class="col-md-12">
					    <div class="row">
						<div class="col-md-12" style="margin-top:6px">

						    <label class="nombre_usuario"></label>

						</div>
					    </div>
					</div>
					<div class="col-md-12">
					    <div class="row">
						<div class="col-md-12" style="margin-top:6px">
						    <label class="rut_usuario"></label>
						</div>
					     </div>
					</div>
					<div class="col-md-12">
					    <div class="row">
						<div class="col-md-12" style="margin-top:6px">
						    <label class="cantidad_alumnos"></label>
						</div>
					     </div>
					</div>
					<div class="col-md-12">
					    <ul class="nav nav-tabs">
						<li class="active"><a href="#"><i class="fa fa-graduation-cap"></i> Alumno(s)</a></li>
						<table class="dataTable" style="border: 1px solid #ddd">
						    <tr style="background-color: #ddd;">
						    <th style="border-right:1px solid #ccc">Rut</th>
						    <th style="border-right:1px solid #ccc">Nombre</th>
						    <th style="border-right:1px solid #ccc">Producto</th>
						    <th>Estado</th>
						    </tr>
						    <tbody class="datos_hijos">

						    </tbody>
						</table>
					    </ul>
					</div>
				    </div>
				</div>
			    </form>
			</div>
		    </div>
		</fieldset>
		<div class="modal-footer">
		    <div class="col-md-12">
			<div class="row">
			    <div class="col-md-5">
				    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar ventana</button>
			    </div>
			    <span class="col-md-2"></span>
			    <div class="col-md-5">
				<button id="pagar" class="btn btn-primary form-control hidden pagar">Ir a pagar</button>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>