
<div class="card bg-light mb-12">
    <div class="card-header">Selección de productos - Ediciones SM </div>
    <div class="card-body text-dark">
	<div class="row" style="border-bottom: 1px solid #E6EAEA; border-top: 1px solid #E6EAEA; margin-top: 20px; padding: 10px;">
	    <div id="definicion1" class="col-xs-12 col-sm-6" >
		<i class="fa fa-hashtag fa-2x" aria-hidden="true"></i>
		<div style="padding:20px" class="card  bg-light col-xs-12 col-sm-6">
		    <label style="font-size: 28px; text-decoration: underline; margin-left: 1%"> Codigos de Compra </label>
		    <div class="form-group row">
    <!--		   <img src="../img/despacho.png" width="225">-->

			<div style="padding:20px; " class="card col-xs-12 col-sm-12">
			    <label class="col-form-label col-xs-4 col-sm-4" >Despacho : </label> <label class="col-form-label col-xs-8 col-sm-8" >BLuexc </label>
			    <label class="col-form-label col-xs-12 col-sm-12" >Codigo OT </label>
			    <label class="col-form-label col-xs-12 col-sm-12" >6465823081</label>
			</div>
		    </div>
		</div>
	    </div>
	    <div id="definicion3" class="col-xs-12 col-sm-6">
		<div class="form-group row">
		    <div class="col-md-12" style="">
			<h4>Seguimiento</h4>
			<i class="carrito_compra" aria-hidden="true"></i>
			<span id="carrito_txt" class="badge badge-dark"></span>
		    </div> 
		    		    <iframe  id="iframess" width='700' height='500' src="http://www.bluex.cl/web/portal-blue-express-chile/nacional" frameborder="0" allowfullscreen></iframe>

		</div>
		
	    </div>
	</div>
    </div>
</div>
<script>
  
  $(document).ready(function(){
    var iFrameDOM = $("iframe#iframess").contents();
	    iFrameDOM.find("html").css("overflow-x","hidden");
	    iFrameDOM.find("html").css("overflow-y","hidden");
    console.log(iFrameDOM);
  });
</script>
<style>
    iframe.html{
	overflow: hidden !important;
    }
</style>
