
<div class="card bg-light mb-12">
    <div class="card-header">Seguimiento de Compras - Ediciones SM </div>
    <div class="card-body text-dark">
<!--	<img src="../img/despacho.png" style="width:10%">-->
	<div class="row" style=" margin-top: 20px; padding: 10px;">
	    <div id="definicion1" class="col-xs-12 col-sm-6" >
		
		<div style="padding:20px" class="card  bg-light col-xs-12 col-sm-6">
		    <label style="font-size: 28px; text-decoration: underline; margin-left: 1%"> 
			<i class="fa fa-hashtag" aria-hidden="true"></i> Codigos de Compra 
		    </label>
		    <div class="form-group row col-sm-12">
			 <?php 
				foreach($codigos as $codigo): ?>
				    <div style="padding:20px; " class="card col-xs-12 col-sm-12">
					<div class="row">
					<label class="col-xs-12 col-sm-12" >Transporte  : <?php echo $codigo->transporte ?></label> 
					</div>
					<div class="row">
					<label class="col-xs-12 col-sm-12" >Codigo OT   : <?php echo $codigo->ot?></label>
					</div>
				    </div>
			<?php	endforeach; ?>
		    </div>
		</div>
	    </div>
	    <div id="definicion3" class="col-xs-12 col-sm-6">
		<div class="form-group row">
		    <div class="col-md-12" style="">
			<h4>Seguimiento <?php echo Session::get('id') ?></h4>
			<i class="carrito_compra" aria-hidden="true"></i>
			<span id="carrito_txt" class="badge badge-dark"></span>
		    </div>
		    		    <iframe  id="iframess" width='700' height='500' src="http://www.bluex.cl/web/portal-blue-express-chile/nacional" frameborder="0" allowfullscreen></iframe>

		</div>

	    </div>
	</div>
    </div>
</div>
<script>

  $(document).ready(function(){
    var iFrameDOM = $("iframe#iframess").contents();
	    iFrameDOM.find("html").css("overflow-x","hidden");
	    iFrameDOM.find("html").css("overflow-y","hidden");
    console.log(iFrameDOM);
  });
</script>
<style>
    iframe.html{
	overflow: hidden !important;
    }
</style>
