<script type="text/javascript">
  $(document).ready(function()
    {
    $("#btn2").click(function () {
      var tipo = $('#apo').val();;//
      $.ajax({
        type: 'POST',
        cache: false,
        url: 'usuario/tipo',
        data: {"tipo": tipo},
        success: function(result){
          console.log(tipo);
          $("#cap").empty().load("usuario/datos");
          //window.location.href = "usuario/datos";
        },
      })
    });
    $("#btn1").click(function () {
      var tipo = $('#profe').val();; //
      $.ajax({
        type: 'POST',
        cache: false,
        url: 'usuario/tipo',
        data: {'tipo': tipo},
        success: function(result){
          console.log(tipo);
          $("#cap").empty().load("usuario/datos");
          //window.location.href = "usuario/datos";
        },
      })
    });
  });
</script>
<br>
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8 col-xs-12 cont-home">
      <div id="cap">
        <div class="card bg-light mb-12 cont-sombra">
          <div class="card-header">Sistema de SMCompra - Ediciones SM</div>
          <div class="card-body text-dark">
            <h4 class="card-title">Asistente de compra</h4>
            <p class="card-text">Este asistente le ayudará al momento de elegir los
                                 textos que necesitas adquirir.</p>
            <h4 class="card-title">Bienvenido</h4>
            <p class="card-text">Por favor, lea todas las instrucciones antes de continuar.</p>
            <p class="card-text">Este asistente está diseñado para que la compra la realice el apoderado del o los alumnos.
    Es muy importante que complete la información con datos reales y de un mayor de edad responsable de la compra, ya que estos serán asociados a la Licencia o Texto que adquiera.</p>
            <p class="card-text">Al presionar en el botón continuar usted declara conocer y comprender las instrucciones de uso del asistente.</p>
              <button id="btn1" type="button" name="button" value="profesor" class="btn btn-primary">Profesor</button>
              <input id="profe" type="hidden" name="" value="profesor">
              <button id="btn2" type="button" name="button" value="apoderado" class="btn btn-primary">Apoderado</button>
              <input id="apo" type="hidden" name="" value="apoderado">
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-2"></div>
    <div id="resp" class="col-xs-12"></div>
  </div>
