<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>SM Compra | Ediciones SM</title>
    <?php Tag::css('lux') ?>
    <?php Tag::css('font') ?>
    <?php Tag::css('smcompra') ?>
    <?= Html::IncludeCss() ?>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  </head>
  <body>
    <?php echo Html::img('fondo.jpg', 'Logo ediciones SM', 'style="width:100%; height: 100%; position:absolute"') ?></a>
    <nav class="navbar navbar-expand-lg navbar-light bg-light col-sm-12">
	<div class="col-md-2"></div>
	<a class="navbar-brand"><?php echo Html::img('logo_tiendasm.png', 'Logo ediciones SM', 'width="160" height="50"') ?></a>
	<div class="collapse navbar-collapse" id="top-navbar-1"></div>
	<ul class="nav navbar-nav navbar-right">
	    <li>
		<span class="li-text">
		    Síguenos en nuestras
		</span>
		<strong>redes</strong>
		<span class="li-text">
		    sociales:
		</span>
		<span class="li-social" >
		    <a href="https://es-la.facebook.com/edicionesSMChile/"><i class="fa fa-facebook fa-2x"></i></a>
		    <a href="https://twitter.com/ediciones_sm?lang=es"><i class="fa fa-twitter fa-2x"></i></a>
		</span>
	    </li>
	</ul>
	<div class="col-md-2"></div>
    </nav>
  <div class="col-sm-2"></div>
    <div class="container-fluid">
      <?php View::content() ?>
    </div>
    <?php View::partial('pie') ?>
  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</html>
