<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset=utf-8>
    <title>ERROR 404</title>
    <meta name=robots content=noindex>
    <meta name=generator content="KumbiaPHP Framework">
    <style>
        body{font-family:arial;
        text-align: center;
        background:#EEE}
        img {
        border: 0;
        max-width: 100%;
        height: auto;
        }
        .logo{padding:0}
        #error-404{padding-top:2%}
        p{font-size:xx-large;}
        h1 {
            color: #fe0000;
            font-size: 112px;
            line-height: 0;
            font-family:"arial black";
        }
        .logo{background:transparent}
        .logo:hover{border:none}
        a{color:#000000;
        background:#CBCBCB;
        border:2px solid #000000;
        padding:.5em 2em;
        border-radius:2em;
        margin-top:1em;
        font-size:large;
        font-weight: bold;
        text-decoration:none}
        a:hover{background:#CBCBCB;
        border:2px solid #fe0000;
        color:#fe0000;}
    </style>
</head>
  <body>
    <div id="error-404">
          <img src="<?= PUBLIC_PATH ?>img/smlogomin.JPG" height="150" width="150"/>
        <h1>404</h1>
        <p>¡OOPS! Esta página no existe.</p>
        <?php echo Html::link('', 'Ir a la página de inicio', 'class="btn btn-default"') ?>
    </div>
  </body>
</html>
