<!-- header info alumno y seleccion hijos -->
<div class="row">
    <div class="col-md-1" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-4">
		<!--aqui columna derecha de algun texto-->
	    </div>
	</div>
    </div>
    <div class="col-md-6" style="border: 0px solid; background-color: #FFF; padding: 15px">
	
    </div>
    <div class="col-md-2" style="border: 0px solid; background-color: #FFF; padding: 15px ">
	
    </div>
    <div class="col-md-2" style="border:0px solid; background-color: #FFF; padding: 15px  ">
	
    </div>
    <div class="col-md-1" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-4">
		<!--aqui columna derecha de algun texto-->
	    </div>
	</div>
    </div>
</div>

<!-- Lienzo separador -->
<div class="row" >
    <div class="col-md-1"></div>
    <div class="col-md-10" style="background-color: #FFF; padding:15px">
	<h4>Filtros de busqueda</h4>
	<div class="row">
	    <div class="col-md-2">
		<select class="form-control">
		    <option>Seleccione asignatura</option>
		</select>
	    </div>
	    <div class="col-md-2">
		<select class="form-control">
		    <option>Seleccione proyecto</option>
		</select>
	    </div>
	    <div class="col-md-5">
		<span class="text-success"><strong><label id="cantidad_productos">0</label> productos encontrados </strong></span>
	    </div>
	</div>
	
    </div>
    <div class="col-md-1"></div>
</div>

<!-- Lista de productos -->
<div class="row">
    <div class="col-md-12" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-1" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-4">
			<!--aqui columna izquierda de algun texto-->
		    </div>
		</div>
	    </div>
	    <div id="alumno_productos" class="col-md-10" style="padding: 0px">
		
	    </div>
	    <div class="col-md-1" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-4">
			<!--aqui columna derecha de algun texto-->
		    </div>
		</div>
	    </div>
	    <div class="col-md-12" style="background-color: #FFF; padding:15px">
			    <?php echo Html::link("carrito/comprar", "Comprar", "class='btn btn-success'");?>

	    </div>
	</div>
    </div>
</div>	


<!-- Boton Añadir a carrito -->

<!--<div class="row">
    <div class="col-md-8" style="border: 1px solid">
	<button class="btn btn-primary pull-right" >Añadir al carrito</button>
    </div>
</div>-->
