<?php echo Tag::js('carrito') ?>

<script>
    $(document).ready(function(){
	console.log("pase");
	var $this = {
	    carro : '<?php echo Session::get("carrito")?>'
	}
	
	 this.construct = function(){
	    $.extend($this);
	};
	var arr = $("#productos").val();
	console.log(arr);
	console.log($this.carro);
	var carrito = new Carrito();
	var table = $('#tabla_compra').DataTable( {
	    "ajax": {
		     "url": "dataTableListarCarrito",
		     "type" : "post",
		     "dataType": "json",
		     "cache": false,
		     "data" : {"arr": $this.carro},
		   },
	    dom: 'Bfrtip',
	    "bFilter": false,
	    "buttons": [
	    ],
	    "iDisplayLength": -1,
	    "columns": [
		{ "data": "imagen", "width":"10%"},
		{ "data": "descripcion", "width":"30%" },
		{ "data": "tipo", "width":"10%" },
		{ "data": "total","width":"20%"  },
	        { "data": "boton","width":"20%"  }
	    ]
	  });
	 
	 $(".table-responsive").on("click", ".despacho", function(e){
	     $.ajax({
		type: "POST",
		cache: false,
		url: "consultarDireccion",
		success: function(data){
		console.log(data);
		    $('#direccion').modal('show');
		    $("#calle").val(data.calle);
		    $("#tipo option[value="+data.tipo+"]").attr('selected', 'selected');
		    $("#numero").val(data.numero);
		    if(data.id_region != null){
			$("#id_region option[value="+data.id_region+"]").attr('selected', 'selected');
			$("#id_comuna").find("option").remove();
			$("#id_comuna").append("<option value='"+data.id_comuna+"'>"+data.nombre_comuna+"</option>").attr('selected', 'selected');
			
		    }
		    $("#adicional").val(data.adicional);
		},
		error: function(){
		    
		}
	     });
	 });
	 
	 //Profesor
	  $("#direccion").on("click", ".pagar", function(e){
	      swal({
		title: '¿Estás seguro que quieres ir a pagar?',
		text: "si aceptas, serás redireccionado a webpay",
		type: 'warning',
		showCancelButton: true,
		confirmButtonColor: '#3085d6',
		cancelButtonColor: '#d33',
		confirmButtonText: 'Si, ir a pagar',
		cancelButtonText: 'Canelar!',
		confirmButtonClass: 'btn btn-success',
		cancelButtonClass: 'btn btn-danger',
		buttonsStyling: true,
		reverseButtons: true
	      }).then((result) => {
		if (result.value) {
		    var datos_direccion = $("#direccion").find("#datos_despacho").serializeArray();
		    console.log(datos_direccion);
		    var arr = $("#productos").val();
		    $.ajax({
		      type: "POST",
		      cache: false,
		      url : "datatableValidarPago",
		      data : {"arr" : $this.carro,
			      "datos_direccion" : datos_direccion},
		      success: function(data){
			  console.log(data);
			    if(data.total != null){
				swal({
				      title: "Datos Actualizados!",
				      text: "Serás redirigido a WebPay en pocos segundos...",
				      type: 'success',
				      button: false,
				      timer: 3000
				});
				setTimeout(function(){
					window.location = "pasarela";
				}, 3000);
			      }else{
				 swal(
				    'Ha ocurrido un error...',
				    'Favor verificar información ingresada, no deben existir campos vacios',
				    'error',
				); 
			      };
			    },
		      error: function(result){
			    swal(
				'Ha ocurrido un error...',
				'Favor verificar información ingresada, no deben existir campos vacios',
				'error',
			    );
		      }
		    });
		} else if (result.dismiss === 'cancel') {
		
		}
	      });

	  });
	  
	  //Apoderado
	  $(".table-responsive").on("click", ".pagar", function(e){
	    var arr = $("#productos").val();
	    $.ajax({
	      type: "POST",
	      cache: false,
	      url : "datatableValidarPago",
	      data: {"arr": $this.carro},
	      success: function(data){
		    window.location = "pasarela";
		    
	      },
	      error: function(result){
		  console.log("error");
	      }
	    });
	  });
	  
	  $("#volver").on("click", function(e){
	      window.location = "../carrito";
	  });
	  
	  $(".table-responsive").on("click", ".eliminar", function(e){
	      var alumno   = $(this).data("alumno");
	      var producto = $(this).data("prod");
	      var item = [alumno, producto]
	      $this.carro = carrito.preCargarCarritoSession($this.carro);
	      $this.carro = carrito.eliminarItem($this.carro, item);
	      console.log( $this.carro);
		$.ajax({
		    type  : "post",
		    cache : false,
		    url   : "setCarrito",
		    data  : {"carro": $this.carro},
		    success : function(data){
			$this.carro = data.replace(/['"]+/g, "");
			 console.log( $this.carro);
			table.destroy();
			$('#tabla_compra').empty();
			createTable();
		    },
		    error   : function(){
			$(".pagar").attr("disabled","disabled");
			console.log("error");
			swal({
			    title: "El carrito esta vacío",
			    text: "Serás redirigido a la selección de productos",
			    type: 'warning',
			    button: false,
			    timer: 3000
			});
			setTimeout(function(){
				window.location = "../carrito";
			}, 3000);
		    }
		});
	  });
		
	  
	  function createTable(){
	       table = $('#tabla_compra').DataTable( {
		    "ajax": {
			     "url": "dataTableListarCarrito",
			     "type" : "post",
			     "dataType": "json",
			     "cache": false,
			     "data" : {"arr": $this.carro},
			   },
		    dom: 'Bfrtip',
		    "bFilter": false,
		    "buttons": [
		    ],
		    "iDisplayLength": -1,
		    "columns": [
			{ "data": "imagen", "width":"10%"},
			{ "data": "descripcion", "width":"30%" },
			{ "data": "tipo", "width":"10%" },
			{ "data": "total","width":"20%"  },
			{ "data": "boton","width":"20%"  }
		    ]
		  });
	  }
	  
	$("#id_region").on("change", function(){
	    var region = $(this).val();
	    $("#id_comuna").find("option").remove();
	    $("#id_comuna").append("<option value='' disabled selected>Seleccione...</option>");
	    $.ajax({
		type : "post",
		cache : false,
		url : "cargarComunas",
		data : {"region" : region},
		success : function(result){
		    $.each(result, function(i,val){
			$("#id_comuna").append("<option value='"+val.id+"'>"+val.nombre+"</option>");
		    });
		},
		error : function(){
		    
		}
	    });
	});
    });

</script>
<style>
    #tabla_compra_info{
	display:none;
    }
    #tabla_compra_paginate{
	visibility: hidden;
    }
</style>
<!-- header info alumno y seleccion hijos -->
<div class="card bg-light mb-12">

    <div class="card-header">Confirmación de compra - Ediciones SM</div>
	<div class="card-body text-dark">
	    <div class="col-xs-12 col-sm-12">
		<?php
		    View::partial("steps", "", $step); 
		?>
	    </div>
	    <!-- contenido -->
	    <div class="row">
		<div class="col-md-12" style="border: 0px solid">
		    <div class="row">

			<div class="col-md-1" style="border: 0px solid">
			    <div class="row">
				<div class="col-md-4">
				    <!--aqui columna izquierda de algun texto-->
				</div>
			    </div>
			</div>
			<div class="table-responsive col-md-10" style="background-color: #FFF;">

			    <h4>Mi Carrito</h4>
			    <table id="tabla_compra" class="display" cellspacing="0" width="100%">
			      <thead>
				  <tr>
				      <th>Imagen</th>
				      <th>Descripcion</th>
				      <th>Tipo</th>
				      <th>Total</th>
				      <th>Opciones</th>
				  </tr>
			      </thead>
			    </table>
			    <button id="volver" class="btn btn-primary" style="margin:20px; cursor:pointer">Volver</button>
			  </div>
			<div class="col-md-1" style="border: 0px solid">
			    <div class="row">
				<div class="col-md-4">
				    <!--aqui columna derecha de algun texto-->
				</div>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	    
	    <input type="hidden" id="productos" value="<?php echo $arr?>">
	    <!-- Modal Verificar Direccion -->
	    <div class="modal fade" id="direccion" tabindex="-1" role="dialog" aria-labelledby="direccionModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
		    <div class="modal-content">
			<div class="modal-header">
			    <h5 class="modal-title" id="direccionModalLabel">Direcci&oacute;n para despacho</h5>
			    <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
				<span aria-hidden="true">&times;</span>
			    </button>
			</div>
			<div class="modal-body">
			    <fieldset>
				<div class="form-bottom">
				    <div class="form-group">
					<form id="datos_despacho" class="form-horizontal">
					    <div class="col-md-12">
						<div class="row">
						    <div class="col-md-12">
							<div class="row">
							    <div class="col-md-2" style="margin-top:6px">
								<label  class="control-label">* Calle</label>
							    </div>
							    <div class="col-md-10">
								<input type="text" id="calle" name="calle" placeholder="Ingresar Calle... " class="form-control form-sm"><br>
							    </div>
							</div>
						    </div>
						    <div class="col-md-12">
							<div class="row">
							    <div class="col-md-4" style="margin-top:6px">
								<label class="control-label">* Tipo Domicilio</label>
							    </div>
							    <div class="col-md-4">
								<select id="tipo" name="tipo" class="form-control form-sm">
								    <option value="0" disabled selected >Seleccione...</option>
								    <option value="1">Casa</option>
								    <option value="2">Depto.</option>
							        </select>
							    </div>
							    <br>
							    <div class="col-md-1" style="margin-top:6px">
								<label for="inputEmail3" class="control-label">N°</label>
							    </div>
							    <div class="col-md-3">
								<input type="text" id="numero" name="numero" required   title="Ingrese Numero" class="form-control form-sm"><br>
							    </div>
							 </div>
						    </div>
	    <!--					<div class="col-md-12">
							<div class="col-md-2">
							    <label for="inputEmail3" class="control-label">Ciudad</label>
							</div>
							<div class="col-md-10">
							    <input type="text" id="ciudad"  class="form-control form-sm"><br>
							</div>
						    </div>-->
						    <div class="col-md-12">
							<div class="col-lg-12">
							    <label for="inputEmail3" class="control-label">Comuna</label>
							</div>
							<div class="col-md-12">
							    <select id="id_comuna" name="id_comuna" class="form-control form-sm" readonly>
								<option value="" disabled selected >Seleccione...</option>
							    </select>
							</div>
						    </div>
						    <div class="col-md-12">
							<div class="col-md-12">
							    <label for="inputEmail3" class="control-label">Región</label>
							</div>
							<div class="col-md-12">
							    <select id="id_region" name="id_region" class="form-control form-sm">
								<option value="" disabled selected >Seleccione...</option>
								<option value="15">Arica y Parinacota</option>
								<option value="1">Tarapacá</option>
								<option value="2">Antofagasta</option>
								<option value="3">Atacama</option>
								<option value="4">Coquimbo</option>
								<option value="5">Valparaiso</option>
								<option value="13">Metropolitana de Santiago</option>
								<option value="6">Libertador General Bernardo O'Higgins</option>
								<option value="7">Maule</option>
								<option value="8">Biobío</option>
								<option value="9">La Araucanía</option>
								<option value="14">Los Ríos</option>
								<option value="10">Los Lagos</option>
								<option value="11">Aisén del General Carlos Ibáñez del Campo</option>
								<option value="12">Magallanes y de la Antártica Chilena</option>
							    </select>
							</div>
						    </div>
						    <div class="col-md-12">
							<div class="col-lg-12">
							    <label for="inputEmail3" class="control-label">Información adicional despacho(opcional)</label>
							</div>
							<div class="col-md-10">
							    <textarea type="text" maxlength="255" id="adicional" name="adicional" class="form-control form-sm"></textarea><br>
							</div>
						    </div>
						</div>
					    </div>
					</form>
				    </div>
				</div>
			    </fieldset>
			    <div class="modal-footer">
				<div class="col-md-12">
				    <div class="row">
					<div class="col-md-5">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar ventana</button>
					</div>
					<span class="col-md-2"></span>
					<div class="col-md-5">
					    <button id="pagar" class="btn btn-primary form-control hidden pagar">Ir a pagar</button>
					</div>
				    </div>
				</div>
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
    </div>
<!-- Boton Añadir a carrito -->

<!--<div class="row">
    <div class="col-md-8" style="border: 1px solid">
	<button class="btn btn-primary pull-right" >Añadir al carrito</button>
    </div>
</div>-->
