<!-- header info alumno y seleccion hijos -->
<div class="row">
    <div class="col-md-1" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-4">
		<!--aqui columna derecha de algun texto-->
	    </div>
	</div>
    </div>
    <div class="col-md-10" style="border: 0px solid; background-color: #FFF; padding: 15px">

    </div>
    <div class="col-md-1" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-4">
		<!--aqui columna derecha de algun texto-->
	    </div>
	</div>
    </div>
</div>

<!-- Lienzo separador -->
<div class="row" >
    <div class="col-md-1"></div>
    <div class="col-md-10" style="background-color: #FFF; padding:15px">

    </div>
    <div class="col-md-1"></div>
</div>

<!-- contenido -->
<div class="row">
    <div class="col-md-12" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-1" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-4">
			<!--aqui columna izquierda de algun texto-->
		    </div>
		</div>
	    </div>
	    <div class="table-responsive col-md-10" style="background-color: #FFF;">
		<h4>Mi Carrito</h4>
		<table id="tabla_compra" class="display" cellspacing="0" width="100%">
		  <thead>
		      <tr>
			  <th>Imagen</th>
			  <th>Descripcion</th>
			  <th>Cantidad</th>
			  <th>Total</th>
			  <th>Opciones</th>
		      </tr>
		  </thead>
		</table>
	      </div>
	    <div class="col-md-1" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-4">
			<!--aqui columna derecha de algun texto-->
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>
<input type="hidden" id="productos" value="<?php echo $arr?>">

<!-- Boton Añadir a carrito -->

<!--<div class="row">
    <div class="col-md-8" style="border: 1px solid">
	<button class="btn btn-primary pull-right" >Añadir al carrito</button>
    </div>
</div>-->
