<div class="alert alert-info">
  <!--<button type="button" class="close" data-dismiss="alert">&times;</button>-->
  <strong>Error en la transacción con Transbank por alguna de las siguientes razones:
  <p>
    <ul>
      <li>Navegador muy antiguo</li>
      <li>Se perdió la sesión de su usuario por que su navegador no permite cookies.</li>
      <li>Actualice su navegador y vuelva a intentar su compra.</li>
    </ul>
  </p>
  </strong>
  <br>
  <?php echo Html::link('../', 'Inicio de plataforma', 'class="btn btn-success"') ?>
</div>
