<div class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Error</strong> en la transacción con Transbank por las siguientes razones:
  <ul>
    <li>Cupo superado</li>
    <li>Rechazo de transacción por la entidad bancaria</li>
  </ul>
  <?php echo Html::link('#', 'Inicio de plataforma', 'class="btn btn-success"') ?>
</div>
