<?php if($mensaje): ?>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Compra anulada por el usuario</strong>
  </div>
<?php else: ?>
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <div class="card bg-light mb-12" style="max-width: 100%">
        <div class="card-header">Resultado de la transacción:</div>
        <div class="card-body">
          <h4 class="card-title text-center">COMPRA EXITOSA</h4>
          <p class="card-text">Le enviamos un correo con la descripción de su compra.</p>
          <p class="card-text">Gracias por comprar con nosotros.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-3"></div>
  </div>
<?php endif ?>
