<?php if($mensaje): ?>
  <div class="alert alert-info">
    <strong>Compra anulada por el usuario</strong>
  </div>
<?php else: ?>
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <div class="card bg-light mb-12" style="max-width: 100%">
        <div class="card-header">Detalle de la compra realizada:</div>
        <div class="card-body text-dark" style="margin:0px, padding-top:0px">
          <div class="col-xs-12 col-sm-12">
        	    <?php View::partial("steps", "", $step); ?>
        	</div>
          <?php //foreach($comprapay as $key => $valor): ?>
            <p><b>Número de orden: <?php echo $comprapay->buyOrder ?></b></p>
            <p><b>Fecha de la compra: <?php echo $comprapay->fecha ?></b></p>
            <p><b>Tipo de Pago: <?php echo $comprapay->tipoPago ?></b></p>
            <p><b>Número de Cuotas: <?php echo $comprapay->cuotas ?></b></p>
            <p><b>Tarjeta Terminada en: <?php echo $comprapay->cardNumber ?></b></p>
            <?php $monto = $comprapay->monto ?>
          <?php //endforeach ?>
          <p>¡Le agradecemos su preferencia!</p>
          <p>Usted ha adquirido los siguientes productos:</p>
          <div class="well">
          <div class="table-responsive">
            <table class="table table-hover table-light">
              <thead>
                <tr>
                  <td><b>PROYECTO</b></td>
                  <td><b>ASIGNATURA/NIVEL</b></td>
                  <td><b>DETALLE</b></td>
                  <td><b>VALOR</b></td>
                </tr>
              </thead>
              <?php foreach ($detalles as $key => $valor): ?>
                <?php foreach ($valor as $key => $value): ?>
                  <tr>
                    <td><?php echo $value->proyecto ?></td>
                    <td><?php echo $value->nombre .' - '.$value->curso ?></td>
                    <td><?php echo $value->codigo ?></td>
                    <td><?php echo 'CLP $'.number_format($value->valor, 0, ' ', '.'); ?></td>
                  </tr>
                <?php endforeach ?>
              <?php endforeach ?>
              <tr>
                <td></td>
                <td></td>
                <td><b>TOTAL</b></td>
                <td><?php echo 'CLP $'.number_format($monto, 0, '', '.') ?></td>
              </tr>
            </table>
            <p>Este email contiene información personal --- Por favor, no lo reenvíe. Si tiene alguna
            llámenos al 600 381 13 12.</p>
            <p>Atentamente,</p>
            <p>Ediciones SM</p>
            <a href='javascript:window.print(); void 0;' class="btn btn-info">Imprima su compra</a>
          </div>
          </div>
      </div>
    </div>
    </div>
    <div class="col-sm-2"></div>
  </div>
<?php endif ?>
