<?php 
$hijos = array(array("id" => "2315", "nombre" => "Francia Alvarez"),
               array("id" => "2316", "nombre" => "Maximiliano Alvares"));
?>
<div id="hijos" data-info='<?php echo json_encode($hijos); ?>'></div>

<script>
   $(document).ready(function(){
        var id_usuario = 689;
        var carrito = [];
        var productos_ini  = "";
	var productos_item = "";
	var productos_fin  = "";
	var productos_full = "";
	var productos = [];
	$.ajax({
	    type  : "POST",
	    cache : false,
	    url   : "carrito/getProductos",
	    data  : {"id_usuario": id_usuario},
	    success: function(data){
		//Carga productos
		var hijos = $("#hijos").data("info");
		var cantidad_productos = data.length;
		var display = 0;
		var mostrar = "block";
		$("#cantidad_productos").text(cantidad_productos);
		$.each( hijos, function( key, val ) {
		    productos_ini  = "";
		    productos_item = "";
		    productos_fin  = "";
		    if(display === 0){
			mostrar = "block";
			dataAlumno(val.id);
		    }else{
			mostrar = "none";
		    }
		    productos_ini = "<div id='alumno"+val.id+"' class='cont-productos col-md-12' style='background-color: #FFF; display:"+mostrar+"'>"+
			            "<div class='row'>";
		
		    $.each(data, function(indice, valor){
			if(val.id === valor.id_alumno){
			    productos_item +=   "<div id='"+valor.id_producto+"' class='col-md-4 producto' data-rel='"+valor.id_producto+"' data-agregado='0' style='border: 0px solid'>"+
						    "<div class='col-md-12 img-hover' style='cursor:pointer;'>"+
							"<div class='row'>"+
							    "<div id='agregado"+valor.id_producto+"' class='col-md-6' style='padding:10px'>"+
								"<img src='/smcompra/img/productos/"+valor.img+"' alt='producto' style='width:70%; position: absolute' />"+	
							    "</div>"+
							    "<div class='col-md-6' style='padding:10px'>"+
								"<h5 class='mt-0'>Asignatura:</h5>"+
								"<p class='card-text'>"+valor.asignatura+"</p>"+
								"<h5>Proyecto:</h5>"+
								"<p class='card-text'>"+valor.proyecto+"</p>"+
								"<p><span><b>Curso: </b></span><span class='card-text'>"+valor.nivel+"</span></p>"+
								"<h5>Tipo Material:</h5>"+
								"<span class='card-text'> "+valor.tipo+" </span>"+
								"<span class='card-text'>$"+valor.valor+"</span>"+
							    "</div>"+
							"</div>"+
						    "</div>"+
						"</div>";
			}
		    });
		    productos_fin = "</div></div>";
		    productos_full = productos_ini + productos_item + productos_fin;
		    productos.push(productos_full);
		    display++;
		});
		
		var  productos_html = "";
		$.each(productos, function(i,val){
		    productos_html += val;
		});
		$("#alumno_productos").html(productos_html);
	    },
	    error: function(data){
	    }
	});
	
       $("#alumno_productos").on("click",".producto", function(e){
	    var id = $(this).data("rel");
	    var agregado_estado = $(this).data("agregado");
	    if(agregado_estado == 0){
		carrito.push(id);
		$("#agregado"+id).append('<img id="img'+id+'" src="/smcompra/img/productos/agregado.png" width="70%" style="position:absolute;"/>');
		$(this).data("agregado","1");
	    }else if(agregado_estado == 1){
		carrito.splice($.inArray(id, carrito),1);
		$("#img"+id).remove();
		$(this).data("agregado","0");
	    }
	    $("#carrito_txt").text(carrito.length);
       });
       
       $(".alumno").on("click",function(e){
	    var id = $(this).data("rel");
	    dataAlumno(id);
	    $(".cont-productos").css("display", "none");
	    $("#alumno"+id).css("display", "block");
       });
       
       function dataAlumno(id){
	$.ajax({
	      type : "POST",
	      cache: false,
	      url  : "carrito/getAlumno",
	      dataType: 'json',
	      data : {"id" : id},
	      success: function(data){
		  $("#nombre_alumno").text(data.nombre);
		  $("#colegio_alumno").text(data.establecimiento_nombre);
		  $("#curso_alumno").text(data.curso);
		  
	      },
	      error: function(data){
		  console.log("err");
	      }
	  }); 
       }
   });
</script>



<!-- header info alumno y seleccion hijos -->
<div class="row">
    <div class="col-md-1" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-4">
		<!--aqui columna derecha de algun texto-->
	    </div>
	</div>
    </div>
    <div class="col-md-6" style="border: 0px solid; background-color: #FFF; padding: 15px">
	<h4>Alumno</h4>
	<p><label>Nombre  : </label><label id="nombre_alumno"></label></p>
	<p><label>Colegio : </label><label id="colegio_alumno"></label></p>
	<p><label>Curso   : </label><label id="curso_alumno"></label></p>
    </div>
    <div class="col-md-2" style="border: 0px solid; background-color: #FFF; padding: 15px ">
	<h4>Carrito</h4>
	<i class="fa fa-shopping-cart fa-5x" aria-hidden="true"></i>
	<span id="carrito_txt" class="badge badge-dark">0</span>
    </div>
    <div class="col-md-2" style="border:0px solid; background-color: #FFF; padding: 15px  ">
	<h4>Hijos</h4>
	<?php 
	    foreach($hijos as $hijo):
		echo '<div class="alumno" data-rel="'.$hijo["id"].'" style="cursor: pointer"><p>'.$hijo["nombre"].'</p></div>';
	    endforeach;
	?>
    </div>
    <div class="col-md-1" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-4">
		<!--aqui columna derecha de algun texto-->
	    </div>
	</div>
    </div>
</div>

<!-- Lienzo separador -->
<div class="row" >
    <div class="col-md-1"></div>
    <div class="col-md-10" style="background-color: #FFF; padding:15px">
	<h4>Filtros de busqueda</h4>
	<div class="row">
	    <div class="col-md-2">
		<select class="form-control">
		    <option>Seleccione asignatura</option>
		</select>
	    </div>
	    <div class="col-md-2">
		<select class="form-control">
		    <option>Seleccione proyecto</option>
		</select>
	    </div>
	    <div class="col-md-5">
		<span class="text-success"><strong><label id="cantidad_productos">0</label> productos encontrados </strong></span>
	    </div>
	</div>
	
    </div>
    <div class="col-md-1"></div>
</div>

<!-- Lista de productos -->
<div class="row">
    <div class="col-md-12" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-1" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-4">
			<!--aqui columna izquierda de algun texto-->
		    </div>
		</div>
	    </div>
	    <div id="alumno_productos" class="col-md-10" style="padding: 0px">
		
	    </div>
	    <div class="col-md-1" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-4">
			<!--aqui columna derecha de algun texto-->
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>	


<!-- Boton Añadir a carrito -->

<!--<div class="row">
    <div class="col-md-8" style="border: 1px solid">
	<button class="btn btn-primary pull-right" >Añadir al carrito</button>
    </div>
</div>-->
