<?php 
$hijos = array(array("id" => "2315", "nombre" => "Francia Alvarez"),
               array("id" => "2316", "nombre" => "Maximiliano Alvares"));
?>
<div id="hijos" data-info='<?php echo json_encode($hijos); ?>'></div>
<?php echo Tag::js('carrito') ?>
<script>
   $(document).ready(function(){
       var carrito = [];
       var  carrito_compra = new Carrito();
       carrito_compra.cargarProductos();
       
       $("#alumno_productos").on("click",".producto", function(e){
	    var id = $(this).data("rel");
	    var agregado_estado = $(this).data("agregado");
	    carrito_compra.agregar(id, agregado_estado);
	    
       });
       
       $(".alumno").on("click",function(e){
	    var id = $(this).data("rel");
	    dataAlumno(id);
	    $(".cont-productos").css("display", "none");
	    $("#alumno"+id).css("display", "block");
       });
   });
</script>



<!-- header info alumno y seleccion hijos -->
<div class="row">
    <div class="col-md-1" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-4">
		<!--aqui columna derecha de algun texto-->
	    </div>
	</div>
    </div>
    <div class="col-md-6" style="border: 0px solid; background-color: #FFF; padding: 15px">
	<h4>Alumno</h4>
	<p><label>Nombre  : </label><label id="nombre_alumno"></label></p>
	<p><label>Colegio : </label><label id="colegio_alumno"></label></p>
	<p><label>Curso   : </label><label id="curso_alumno"></label></p>
    </div>
    <div class="col-md-2" style="border: 0px solid; background-color: #FFF; padding: 15px ">
	<h4>Carrito</h4>
	<i class="fa fa-shopping-cart fa-5x" aria-hidden="true"></i>
	<span id="carrito_txt" class="badge badge-dark">0</span>
    </div>
    <div class="col-md-2" style="border:0px solid; background-color: #FFF; padding: 15px  ">
	<h4>Hijos</h4>
	<?php 
	    foreach($hijos as $hijo):
		echo '<div class="alumno" data-rel="'.$hijo["id"].'" style="cursor: pointer"><p>'.$hijo["nombre"].'</p></div>';
	    endforeach;
	?>
    </div>
    <div class="col-md-1" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-4">
		<!--aqui columna derecha de algun texto-->
	    </div>
	</div>
    </div>
</div>

<!-- Lienzo separador -->
<div class="row" >
    <div class="col-md-1"></div>
    <div class="col-md-10" style="background-color: #FFF; padding:15px">
	<h4>Filtros de busqueda</h4>
	<div class="row">
	    <div class="col-md-2">
		<select class="form-control">
		    <option>Seleccione asignatura</option>
		</select>
	    </div>
	    <div class="col-md-2">
		<select class="form-control">
		    <option>Seleccione proyecto</option>
		</select>
	    </div>
	    <div class="col-md-5">
		<span class="text-success"><strong><label id="cantidad_productos">0</label> productos encontrados </strong></span>
	    </div>
	</div>
	
    </div>
    <div class="col-md-1"></div>
</div>

<!-- Lista de productos -->
<div class="row">
    <div class="col-md-12" style="border: 0px solid">
	<div class="row">
	    <div class="col-md-1" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-4">
			<!--aqui columna izquierda de algun texto-->
		    </div>
		</div>
	    </div>
	    <div id="alumno_productos" class="col-md-10" style="padding: 0px">
		
	    </div>
	    <div class="col-md-1" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-4">
			<!--aqui columna derecha de algun texto-->
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>	


<!-- Boton Añadir a carrito -->

<!--<div class="row">
    <div class="col-md-8" style="border: 1px solid">
	<button class="btn btn-primary pull-right" >Añadir al carrito</button>
    </div>
</div>-->
