<?php 
$hijos = array();
$i=0;
//print_r($alumno);die();
foreach($alumno as $al):
    $hijos[$i]["id"] = $al->id;
    $hijos[$i]["nombre"] = $al->nombre;
    $i++;
endforeach;
?>
<div id="hijos" data-info='<?php echo json_encode($hijos); ?>'></div>
<div id="usuario" data-info='<?php echo json_encode($usuario); ?>'></div>
<div id="tipo" data-info='<?php echo json_encode($tipo); ?>'></div>
<div id="carrito" data-info='<?php echo (!empty(Session::get("carrito")))? json_encode(Session::get("carrito")):  ""; ?>'></div>

<?php echo Tag::js('carrito') ?>
<?php echo Tag::js('index_carrito') ?>
<script>
    $('.guia').on('click', function(e){ 
	startIntro();
    });
	function startIntro(){
	     var intro = introJs();
	       intro.setOptions({
		 steps: [
		   { 
		     intro: "<div style='width:320px'><div style='width:300px; text-align:justify'>Bienvenido al Sistema de Compras de Ediciones SM. <br>Complete el inductivo hasta el final para conocer todas las funcionalidades que proporciona el sistema. </div><br> <strong>Suerte!</strong> </div>",
		     position: 'top'
		    },
		   {
		     element: document.querySelector('#definicion1'),
		     intro: "Este bloque determina el alumno al cual se le están comprando los productos"
		   },
		   {
		     element: document.querySelectorAll('#definicion2')[0],
		     intro: "Aquí podrá determinar a que pupilo(a) se le compraran los productos. Al seleccionar alguno quedara reflejado en el paso anteriormente señalado.",
		     position: 'left'
		   },
		   {
		     element: document.querySelectorAll('#definicion3')[0],
		     intro: 'Este es el carrito de compra, aquí podra visualizar la cantidad de productos añadidos al carrito.',
		     position: 'left'
		   },
		   {
		     element: document.querySelectorAll('.definicion4')[0],
		     intro: "Este es nuestro visualizador y seleccionador de productos. <br> En esta sección podrá visualizar todos los productos disponibles para su pupilo(a).",
		     position: 'top'
		   },
		   {
		     intro: 'Fin'
		   }
		 ]
	       });
	       intro.start();
	   }
    </script>
</script>
<!-- header info alumno y seleccion hijos -->

<div class="card bg-light mb-12">
    <div class="card-header">Selección de productos - Ediciones SM</div>
    <div class="card-body text-dark">
	<div class="col-xs-12 col-sm-12">
	    <?php View::partial("steps", "", $step); ?>
	</div>
<!--	<h2 class="card-title">Paso 3 / 5</h2>-->
	<div class="row" style="border-bottom: 1px solid #E6EAEA; border-top: 1px solid #E6EAEA; margin-top: 20px; padding: 10px;">
	    <div id="definicion1" class="col-xs-12 col-sm-6">
		<i class="fa fa-user fa-2x" aria-hidden="true"></i><label style="font-size: 28px; text-decoration: underline; margin-left: 1%"> Alumno </label>
		<div class="form-group row">
		    <label class="col-form-label col-sm-2" >Nombre  :</label><label class="col-form-label col-sm-10 nombre_alumno"></label>
		    <label class="col-form-label col-sm-2" >Colegio : </label><label class="col-form-label col-sm-10" id="colegio_alumno"></label>
		    <label class="col-form-label col-sm-2" >Curso   : </label><label class="col-form-label col-sm-10" id="curso_alumno"></label>
		</div>
	    </div>
	    <div id="definicion2" class="col-xs-12 col-sm-4">
		<i class="fa fa-graduation-cap fa-2x" aria-hidden="true"></i><label style="font-size: 28px; text-decoration: underline"> Hijos </label>
		<div class="form-group row">
		<?php 
		    foreach($hijos as $hijo):
			echo '<div class="alumno col-sm-12" data-rel="'.$hijo["id"].'"><label class="col-form-label alumno_select"  style="cursor: pointer"><i class="fa fa-user" aria-hidden="true"></i> '.$hijo["nombre"].'</label></div>';
		    endforeach;
		?>
		</div>
	    </div>
	    <div id="definicion3" class="col-xs-12 col-sm-2">
		<div class="form-group row">
		    <div class="col-md-12" style="">
		    <h4>Carrito</h4>
		    <i class="carrito_compra fa fa-shopping-cart fa-5x" aria-hidden="true"></i>
		    <span id="carrito_txt" class="badge badge-dark">0</span>
		    </div>
		</div>
	    </div>
	</div>

<!-- Lienzo separador -->
	<div class="row" id="lienzo">
	    <div class="col-md-1"></div>
	    <div class="col-md-10" style=" padding:15px">
		
		<div class="row">
		    <div class="col-md-6">
			<h4 style="float:left">Lista de Productos </h4>
			<button class="btn btn-primary todos">Comprar Todo</button>
		    </div>
		    <div class="col-md-6">
			<span class="text-success" style="float:right; margin-top:15px"><strong><label id="cantidad_productos">0</label> productos encontrados </strong></span>
		    </div>
		</div>
	    </div>
	    <div class="col-md-1"></div>
	</div>

<!-- Lista de productos -->
	<div  class="row">
	    <div class="col-md-12" style="border: 0px solid">
		<div class="row">
		    <div class="col-md-1" style="border: 0px solid">
			<div class="row">
			    <div class="col-md-4">
				<!--aqui columna izquierda de algun texto-->
			    </div>
			</div>
		    </div>
		    <div id="alumno_productos" class="col-md-10 definicion4" style="padding: 0px">
			<div class="loading">Cargando lista de productos...</div>
		    </div>
		    <div class="col-md-1" style="border: 0px solid">
			<div class="row">
			    <div class="col-md-4">
				<!--aqui columna derecha de algun texto-->
			    </div>
			</div>
		    </div>
		    <div class="col-md-1" style="border: 0px solid">
			<div class="row">
			    <div class="col-md-4">
				<!--aqui columna izquierda de algun texto-->
			    </div>
			</div>
		    </div>
		    <div class="col-md-10" style=" padding:15px">
			<form method="post" action="carrito/comprar" style="display:none">
			    <input id="productos_arr" name="productos_arr" value="" class="hidden">
			    <input id="id_usuario" name="id_usuario" value="" class="hidden">
			    <input id="productos_submit" type="submit" class="hidden">
			</form>
			<hr>
			<button id="continuar_comprar" class="btn btn-success">Continuar</button>
		    </div>
		    <div class="col-md-1" style="border: 0px solid">
			<div class="row">
			    <div class="col-md-4">
				<!--aqui columna derecha de algun texto-->
			    </div>
			</div>
		    </div>
		</div>
	    </div>
	</div>
    </div>
</div>


<!-- Boton Añadir a carrito -->

<!--<div class="row">
    <div class="col-md-8" style="border: 1px solid">
	<button class="btn btn-primary pull-right" >Añadir al carrito</button>
    </div>
</div>-->
