<?php if($errorpay): ?>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Error</strong> en la transacción con Transbank por las siguientes razones:
    <ul>
      <li>Cupo superado</li>
      <li>Rechazo de transacción por la entidad bancaria</li>
    </ul>
    <?php echo Html::link('#', 'Inicio de plataforma', 'class="btn btn-success"') ?>
  </div>
<?php else: ?>
  <form name="webpay" action="<?=$result->urlRedirection?>" method="post">
      <input type="text" name="token_ws" value="<?=$token?>" />
      <input type="submit" value="enviar" />
  </form>
  <script>
    window.onload=function(){
    // Una vez cargada la página, el formulario se enviara automáticamente
    document.webpay.submit();
    }
  </script>
<?php endif ?>
