<?php if($errorpay): ?>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Error</strong> en la transacción con Transbank por las siguientes razones:
    <ul>
      <li>Cupo superado</li>
      <li>Rechazo de transacción por la entidad bancaria</li>
    </ul>
    <?php echo Html::link('#', 'Inicio de plataforma', 'class="btn btn-success"') ?>
  </div>
<?php else: ?>
<?php
  $tipo = Session::get('tipo');
?>
    <?php if($tipo == 1): ?>
    <?php echo Tag::js("libros"); ?>
    <?php echo Tag::js("licencias"); ?>
    <script>
	$(document).ready(function(){
	   var rest_libros = new Libros({"carrito" : <?php echo Session::get("carrito") ?>,
	                                 "flujo"   : <?php echo json_encode($data_alumnos)?> });

	});
    </script>
<?php endif;?>
  <form class="webpay" name="webpay" action="<?=$result->urlRedirection?>" method="post">
      <input type="text" name="token_ws" value="<?=$token?>" />
      <input class="submit_btn" type="submit" value="" style="display:none" />
  </form>
  <script>
    window.onload=function(){
    // Una vez cargada la página, el formulario se enviara automáticamente
    document.webpay.submit();
    }
  </script>
<?php endif ?>
