<?php if($errorpay): ?>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Error</strong> en la transacción con Transbank por las siguientes razones:
    <ul>
      <li>Cupo superado</li>
      <li>Rechazo de transacción por la entidad bancaria</li>
    </ul>
    <?php echo Html::link('#', 'Inicio de plataforma', 'class="btn btn-success"') ?>
  </div>
<?php else: ?>
<?php
    echo Tag::js('jquery3');
    $tipo = Session::get('tipo');
  
?>
    <?php if($tipo == 1): ?>
    
    <?php echo Tag::js("libros"); ?>
    <?php echo Tag::js("licencias"); ?>
    <script>
	
	   var rest_libros = new Libros({"carrito" : <?php echo $_COOKIE["carritoSM"] ?>,
	                                 "flujo"   : <?php echo json_encode($data_alumnos)?> });

	
    </script>
    <?php else: ?>
   <script>
       $(document).ready(function(){
	    $("#regreso").trigger("click");
       });
  </script>
    
     <?php endif; ?>
    <form name="webpay" action="<?=$result->urlRedirection?>" method="post">
      <input type="text" name="token_ws" value="<?=$token?>" style="display:none"/>
      <input id="regreso" type="submit" value="" style="display:none" />
    </form>

<?php endif ?>
