<div class="row">
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Ventas totales</span>
        <span class="info-box-number"><?php echo $ventatotal->venta?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Pago en despacho</span>
        <span class="info-box-number"><?php echo $despacho ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Ingresos menos despacho</span>
        <span class="info-box-number"><?php echo $ventatotal->venta - $despacho ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
</div>
