<?php echo Tag::js("../bower_components/charts/dist/chart") ?>
<?php echo Tag::js("administrador/estadisticas/graficos") ?>
<div class="row">
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Ventas totales</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($ventatotal->venta, 0, ' ', '.')?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Pago en despacho</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($despacho, 0, ' ', '.')  ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Ingresos menos despacho</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($ventatotal->venta - $despacho, 0, ' ', '.')  ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
</div>
<hr>
<!-- Licencias totales, vendidas y por vender -->
<div class="row">
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-red"><i class="ion ion-cash"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Ventas total de Licencias</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format( $licencias, 0, ' ', '.')  ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-red"><i class="ion ion-cash"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Venta total de textos</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($textos, 0, ' ', '.')  ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-red"><i class="ion-cash"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Otra</span>
        <span class="info-box-number"><?php echo $licenciaGlobal ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
</div>
<hr>
<!-- Licencia globales y textos globales -->
<div class="row">
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-paper"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Licencias globales</span>
        <span class="info-box-number"><?php echo $licenciaGlobal ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-paper"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Licencias vendidas</span>
        <span class="info-box-number"><?php echo $licVenta ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-paper"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Licencias restantes por vender</span>
        <span class="info-box-number"><?php echo $licenciaGlobal - $licVenta ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
</div>
<hr>
<!-- Textos globales, textos comprados, textos restantes por comprar -->
<div class="row">
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-green"><i class="ion ion-document-text"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Textos globales</span>
        <span class="info-box-number"><?php echo $textoGlobal ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-green"><i class="ion ion-document-text"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Textos vendidos</span>
        <span class="info-box-number"><?php echo $texVenta ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-green"><i class="ion ion-document-text"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Textos restantes por vender</span>
        <span class="info-box-number"><?php echo $textoGlobal - $texVenta ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
</div>
<hr>
<!-- Globales de textos y licencias -->
<div class="row">
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-red"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Total global Licencias</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($globalTotalLic, 0, ' ', '.')  ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-red"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Total global Textos</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($globalTotalTex, 0, ' ', '.') ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-red"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Total Licencias y textos</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($globalTotalLic + $globalTotalTex, 0, ' ', '.')  ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
</div>
<hr>
<!-- Globales de textos y licencias -->
<div class="row">
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Total restante Licencias</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($globalTotalLic - $licencias, 0, ' ', '.')  ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Total restante Textos</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($globalTotalTex - $textos - $despacho, 0, ' ', '.') ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
  <div class="col-sm-4">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="ion ion-ios-cart-outline"></i></span>
      <div class="info-box-content">
        <span class="info-box-text">Total restante Licencias y textos</span>
        <span class="info-box-number"><?php echo 'CLP $'.number_format($globalTotalLic + $globalTotalTex - $ventatotal->venta - $despacho, 0, ' ', '.')  ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
  </div>
</div>
<div class="row">
<!-- Grafico N°1 : Torta de licencias vendidas en porcentaje -->
  <div class="col-md-6">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Licencias</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
          <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div class="chart">
          <canvas id="chart1" width="510" height="250"></canvas>
        </div>
      </div>
    </div>
  </div>
<!-- Fin grafico N°1 -->
<!-- Grafico N°2 : Torta por texto vendido en porcentaje -->
  <div class="col-md-6">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Textos</h3>

        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
          <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div class="chart">
          <canvas id="chart2" width="510" height="250"></canvas>
        </div>
      </div>
    </div>
  </div>
<!-- Fin grafico N°2 -->
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $.ajax({
      type    : "GET",
      cache   : false,
      url     : "licPorcentaje",
      success: function(result) {
          var grafico_na = new Graficos({tipo    : "line",
                                         canvas  : "chart1",
                                         legenda : "Porcentaje de ventas Licencias"});
          grafico_na.estadistica5(result);
      }
    });
    $.ajax({
      type    : "GET",
      cache   : false,
      url     : "texPorcentaje",
      success: function(result) {
          var grafico_nb = new Graficos({tipo    : "line",
                                         canvas  : "chart2",
                                         legenda : "Porcentaje de ventas Textos"});
          grafico_nb.estadistica6(result);
      }
    });
  })
</script>
