<?php Tag::css('../bower_components/datatables.net-bs/css/dataTables.bootstrap.min') ?>
<script type="text/javascript">
  $(document).ready(function(){
    var table = $('#tabla_historial').DataTable( {
      "ajax": {
               "url": "compras_productos",
               "dataSrc":"",
               "dataType": "json",
               "cache": false,
             },
      dom: 'Bfrtip',
      "buttons": [
         {"extend": 'excel', "text":'<i class="fa fa-download" aria-hidden="true"></i>&nbsp; &nbsp; Exportar Excel',"className": 'btn btn-success pull-center'}
      ],
      "columns": [
          { "data": "id" },
      	  { "data": "buyOrder" },
      	  { "data": "cuotas" },
      	  { "data": "tipoPago" },
      	  { "data": "codigoRespuesta" },
          { "data": "monto" },
          { "data": "fecha" }
      ]
    });
  })
</script>
<div class="row">
  <div class="col-xs-12">
    <h3 class="text-center">Historial de compra de licencias</h3>
  </div>
  <div class="col-sm-1"></div>
  <div class="col-sm-10">
    <div class="table-responsive">
      <table id="tabla_historial" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>Orden de compra</th>
            <th>cuotas</th>
            <th>Forma de pago</th>
            <th>Respuesta Transbank</th>
            <th>Monto</th>
            <th>Fecha</th>
          </tr>
        </thead>
      </table>
    </div>
    <?php echo Html::link('administrador', 'Volver al administrador', 'class="btn btn-success"') ?>
  </div>
  <div class="col-sm-1"></div>
</div>
