<div class="row">
  <div class="col-xs-12">
    <h3 class="text-center">Historial de las órdenes</h3>
  </div>
  <div class="col-sm-1"></div>
  <div class="col-sm-10">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title pull-left"> Lista de Apoderados </h3>
        <br><p>
        <button  class="btn btn-success nuevo_usuario pull-right">
          <i class="fa fa-plus pull-left"> Nuevo </i>
        </button>
        <br>
        <hr>
        <div class="table-responsive">
          <table id="tabla_historial" class="table table-striped table-bordered">
            <thead>
              <tr>
                
              </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
    <?php echo Html::link('administrador', 'Volver al administrador', 'class="btn btn-success"') ?>
  </div>
  <div class="col-sm-1"></div>
</div>
