<script type="text/javascript">
//......................
//funcion para darle formato al active de la barra de menu
//......................
window.onload=function()
{
  document.getElementById("menu1").style.background="#840f00";
  document.getElementById("menu1").style.color="#fbfbfb";
}
</script>
<div class="row">
  <div class="col-md-6">
   
  </div>

  <div class="col-md-6">
    
  </div>

  <div class="col-md-6">
   
  </div>

  <div class="col-md-6">
   
  </div>
</div>
