<script type="text/javascript">
//......................
//funcion para darle formato al active de la barra de menu
//......................
window.onload=function()
{
  document.getElementById("menu1").style.background="#840f00";
  document.getElementById("menu1").style.color="#fbfbfb";
}
</script>
<div class="row">
  <div class="col-sm-6">
    <div class="box box-solid">
      <div class="box-body">
        <h4 class="text-center">
          VISTA PRINCIPAL
        </h4>
        <div class="media">
          <div class="media-body">
            <p>En el lado izquierdo de la plataforma tienes un menú con diferentes opciones, que según tu nivel de acceso, podrás visualizarla en la plataforma.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="box box-solid">
      <div class="box-body">
        <h4 class="text-center">
          ¿DUDAS?
        </h4>
        <div class="media">
          <div class="media-body">
            <p>Si tienes alguna duda con respecto al uso de la plataforma de la tienda, o no puedes visualizar algún módulo que te corresponda, escribe al correo:
            <a href="mailto:yickson.ramirez@ediciones-sm.cl">Yickson.ramirez@ediciones-sm.cl</a>
            </p>
            <p><a href="mailto:cristian.rojas@ediciones-sm.cl">Cristian.rojas@ediciones-sm.cl</a></p>
            <p>Si crees que a la plataforma le hace falta alguna funcionalidad, puedes notificarlo al correo, y analizaremos si procede realizar dicho cambio.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
